name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Build JS files
        env:
          SLUG: tic-tac-toe
        run: |
          npm i
          npm run build-only -- --base="/$SLUG/"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
